### ISSUE TITLE
public static int daysInYear(int year): Gibt die Anzahl der Jahre in dem Jahr zurück.

### ISSUE THREAD

**Issue by Mohamad-1311** [dabrowskiw/Programmierung1-Materialien#10]
Soll die Methode in der Übungsaufgabe in Woche 10, die Anzahl der Jahre oder eher die Anzahl der Tage zurückgeben?
@dabrowskiw

**Comment by Mohamad-1311** [comment]
In der nächsten Methode, schneit auch hier ein Fehler bei der Funktionalität der Methode zu sein: public static int daysInMonth(int month, int year): Gibt die Anzahl der Tage in dem **Jahr** zurück. @dabrowskiw

**Comment by dabrowskiw** [comment]
Vielen dank! Erledigt mit 239db9b2c149d02f90101d5e51e30c141797116b
